global:
  scrape_interval: 5s
  external_labels:
    monitor: 'example-monitoring'
scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']